version: '3.8'

services:

  postgres:
      image: postgres:14
      environment:
          POSTGRES_USER: "developer"
          POSTGRES_PASSWORD: "developer"
          POSTGRES_DB: "dev_database"
      container_name: database
      volumes:
        - ./postgresScripts/variavel-schema.sql:/docker-entrypoint-initdb.d/variavel-schema.sql
        - ./csvFiles/dados_unb.csv:/csvFiles/dados_unb.csv
      ports:
          - "5432:5432"
      networks: 
            backend:
                ipv4_address: 172.25.0.2

  controle:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/visualeasy-controle
      - /visualeasy-controle/node_modules
    container_name: controle
    links:
      - postgres
    ports:
     - "8080:8080"
    environment:
      - NODE_ENV=development
    networks: 
            backend:
                ipv4_address: 172.25.0.3

networks:
  backend:        
    driver: "bridge"
    ipam:
        config:
            - subnet: 172.25.0.0/16
              gateway: 172.25.0.1